apiVersion: apps/v1
kind: Deployment
metadata:
  name: log4shell-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log4shell-demo
  template:
    metadata:
      labels:
        app: log4shell-demo
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
      - name: log4shell-demo
        image: gru.ocir.io/fortinetoraclecloud1/log4shell-fgallego:<TAG>
        imagePullPolicy: "Always"
        securityContext: 
          allowPrivilegeEscalation: false
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: ocirsecret
---
kind: Service
apiVersion: v1
metadata:
  name: log4shell-demo
spec:
  type: LoadBalancer
  selector:
    app: log4shell-demo
  ports:
  - name: http
    port: 8080
    targetPort: 8080
